spring:
  jpa:
    database: POSTGRESQL
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/basewebdb
    username: postgres
    password: 123456





